name: Download and Notarize File

on:
  push:
    branches:
      - main

jobs:
  notarize:
    runs-on: macOS-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download file from 182.198.11.100
        run: |
          # Replace this with the actual command to download the file from the IP address.
          # You can use 'curl' or other relevant tools.
          #curl -o s.zip http://161.35.226.248:9000/s.zip
          brew install cliclick
          cliclick  c:.
          echo $?
          defaults write com.apple.screencapture location "$current_dir"
          killall SystemUIServer
          sleep 1
          screencapture "$current_dir/screenshot_$(date +%Y%m%d%H%M%S).png"
          defaults write com.apple.screencapture location ~/Desktop
          killall SystemUIServer
          ls -alrt
      # You would need to add additional steps here to perform notarization.
      # The specific notarization process depends on your application and requirements.

      # Example: Sign and notarize a macOS app
      - name: Sign and Notarize macOS App
        run: |
          # Replace this with your code signing and notarization commands.
          # This is just a placeholder example.
        #  xcrun notarytool submit s.zip --apple-id "deljwviuro@yahoo.com" --team-id "49T3Z5327K" --password "vqcn-zywi-nrfx-vinr"  --wait
      
